### ISSUE TITLE
Download links on the website are broken

### ISSUE THREAD

**Issue by AliSajid** [common-fate/granted#217]
Hi,

I was trying to install granted on a couple new computers and I see that the links for downloading granted for linux and windows are broken.

Can you please fix that? I'd be happy to help out!

**Comment by JoshuaWilkes** [comment]
Hi @AliSajid 
We were experiencing some issues with our Linux builds, the issue is now resolved, could you please try again now?

**Comment by AliSajid** [comment]
I checked it. The problem persists with 0.2.7 but the link on the website now is for 0.2.6 so that works. Thank you.
